server:
  port: 40001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: 192.168.7.160:9092
      group-id: group-id-pgrrr      
      auto-offset-reset: earliest      
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer      
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer    
    producer:      
      bootstrap-servers: 192.168.7.160:9092      
      key-serializer: org.apache.kafka.common.serialization.StringSerializer      
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
