server:
  port: 40001

spring:
  datasource:
    url: jdbc:h2:mem:menu
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
#    url: jdbc:mysql://localhost:3306/uahannam
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace